import { Money } from '../../products/domain/value-objects/money.vo';
import { Quantity } from '../../products/domain/value-objects/quantity.vo';
import { AppResultAsync } from '../../shared/result/result.types';
import { Transaction, TransactionDeliveryInfo } from './transaction.entity';
import { TransactionStatus } from './transaction-status.vo';

export interface CreatePendingTransactionInput {
  /**
   * The client-supplied idempotency key (a UUID v4, see
   * `CreateTransactionDto.idempotencyKey`) — used directly as the
   * transaction's id so a retried checkout request with the same key always
   * lands on the same row instead of creating a duplicate.
   */
  id: string;
  reference: string;
  customerId: string;
  productId: string;
  quantity: Quantity;
  unitPrice: Money;
  baseFee: Money;
  deliveryFee: Money;
  totalAmount: Money;
  delivery: TransactionDeliveryInfo;
  createdAt: string;
  /**
   * Set only when `POST /transactions` carried a valid Bearer token (PR6's
   * `OptionalJwtAuthGuard`) — omitted entirely for a guest checkout, in
   * which case NO `userId` attribute is written at all (see
   * `DynamoTransactionRepository.createPending`'s guest-checkout regression
   * test). Never present on an idempotent replay's re-read either, unless
   * the ORIGINAL request that created the row already carried it.
   */
  userId?: string;
}

export interface CreatePendingResult {
  transaction: Transaction;
  /**
   * `false` means `id` already existed (an idempotent replay of a prior
   * request with the same `idempotencyKey`) and `transaction` is that
   * pre-existing row, unchanged — callers MUST NOT charge the gateway again
   * in that case. `true` means a brand-new PENDING row was just inserted.
   */
  wasCreated: boolean;
}

export interface UpdateGatewayResultInput {
  gatewayTransactionId?: string;
  status: TransactionStatus;
  lastGatewayCheckAt?: string;
  updatedAt: string;
}

/**
 * Everything `settleApproved` needs to atomically transition a transaction
 * to APPROVED, decrement stock, and create its delivery in one
 * `TransactWriteItems` — see design's settlement snippet. `deliveryId` is
 * generated by the caller (`SettleTransactionUseCase`, via `IdGeneratorPort`)
 * so the repository stays free of id-generation concerns.
 */
export interface SettleApprovedInput {
  transactionId: string;
  productId: string;
  quantity: Quantity;
  customerId: string;
  delivery: TransactionDeliveryInfo;
  deliveryId: string;
  gatewayTransactionId?: string;
  updatedAt: string;
}

/** A terminal, non-approved gateway outcome — never has stock/delivery side effects. */
export interface FinalizeNonApprovedInput {
  transactionId: string;
  status: Exclude<TransactionStatus, 'PENDING' | 'APPROVED'>;
  gatewayTransactionId?: string;
  updatedAt: string;
}

export interface TransactionRepositoryPort {
  /**
   * Idempotent by `input.id`: if a transaction with this id already exists
   * (a replay of a request with the same `idempotencyKey`), returns that
   * existing row with `wasCreated: false` instead of failing or overwriting
   * it. Never re-runs any side effect implied by a fresh creation.
   */
  createPending(input: CreatePendingTransactionInput): AppResultAsync<CreatePendingResult>;
  /**
   * Updates a transaction's gateway-derived fields (status, and optionally
   * `gatewayTransactionId`/`lastGatewayCheckAt`). `gatewayTransactionId` is
   * omitted when the gateway call itself failed (network error/timeout) —
   * the transaction still transitions to `ERROR` in that case, just without
   * a gateway-issued id to reference. NOT condition-guarded — only safe to
   * call when no concurrent settlement of the same transaction is possible
   * (e.g. right after `createPending`, while still PENDING and unknown to
   * any other caller).
   */
  updateGatewayResult(id: string, input: UpdateGatewayResultInput): AppResultAsync<Transaction>;
  /**
   * Atomically (via `TransactWriteItems`, conditioned on the transaction
   * still being PENDING) transitions the transaction to APPROVED, decrements
   * the product's stock, and creates its delivery. Never errors on a benign
   * race: if a concurrent settle attempt already won (webhook vs. lazy-poll),
   * this re-reads and returns the current (already-settled) transaction
   * instead of failing. If the transaction-status condition passes but stock
   * has been oversold by a genuine race, the transaction is still marked
   * APPROVED (the buyer was already charged) WITHOUT decrementing stock or
   * creating a delivery, and the anomaly is logged for manual reconciliation
   * — see `SettleTransactionUseCase`.
   */
  settleApproved(input: SettleApprovedInput): AppResultAsync<Transaction>;
  /**
   * Conditioned (status = PENDING) update to a terminal non-approved status.
   * A benign race (already finalized by a concurrent caller) is resolved by
   * re-reading and returning the current transaction, never as an error.
   */
  finalizeNonApproved(input: FinalizeNonApprovedInput): AppResultAsync<Transaction>;
  /**
   * Records the moment a lazy-poll last checked the gateway, independent of
   * whether the status changed. Best-effort: failures here must never fail
   * the caller's read path (see `GetTransactionUseCase`).
   */
  touchLastGatewayCheckAt(transactionId: string, lastGatewayCheckAt: string): AppResultAsync<void>;
  findById(id: string): AppResultAsync<Transaction>;
  /** Webhook lookup path 1 (preferred). Returns `null`, never an error, when unknown. */
  findByGatewayTransactionId(gatewayTransactionId: string): AppResultAsync<Transaction | null>;
  /** Webhook lookup path 2 (fallback, e.g. gatewayTransactionId not yet persisted). */
  findByReference(reference: string): AppResultAsync<Transaction | null>;
  /**
   * Queries the additive `UserIdIndex` GSI for every transaction belonging
   * to `userId` (PR6's `GET /me/transactions`) — never returns another
   * user's or a guest's transactions. The GSI has no sort key, so ordering
   * (newest first) and capping happen in the adapter after the query; a
   * demo-scale workload never approaches needing real pagination — see
   * `DynamoTransactionRepository.findByUserId`'s own cap constant.
   */
  findByUserId(userId: string): AppResultAsync<Transaction[]>;
}

export const TRANSACTION_REPOSITORY_PORT = Symbol('TRANSACTION_REPOSITORY_PORT');
